<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'cluster/cluster/view' => __DIR__ . '//view/cluster/cluster/view.twig',
    'cluster/cluster/new'  => __DIR__ . '//view/cluster/cluster/new.twig',
    'cluster/cluster/list' => __DIR__ . '//view/cluster/cluster/list.twig',
    'cluster/cluster/edit' => __DIR__ . '//view/cluster/cluster/edit.twig',
);
