<?php

// Generated by ZF2's ./bin/templatemap_generator.php
return [
    'cluster/cluster/reporting'  => __DIR__ . '//view/cluster/cluster/reporting.twig',
    'cluster/admin/cluster/view' => __DIR__ . '//view/cluster/admin/cluster/view.twig',
    'cluster/admin/cluster/new'  => __DIR__ . '//view/cluster/admin/cluster/new.twig',
    'cluster/admin/cluster/list' => __DIR__ . '//view/cluster/admin/cluster/list.twig',
    'cluster/admin/cluster/edit' => __DIR__ . '//view/cluster/admin/cluster/edit.twig',
];
